In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [3]:
reviews=['nice food','amazing restaurant','too good','just loved it!','will go again','horrible food','never go there',
         'poor service','poor quality','needs improvement']
sentiment=np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
one_hot('amazing restaurant',30)

[2, 26]

In [5]:
vocab_size=30
encoded_reviews=[one_hot(d,vocab_size) for d in reviews]
encoded_reviews

[[29, 10],
 [2, 26],
 [28, 2],
 [13, 19, 4],
 [21, 2, 25],
 [11, 10],
 [17, 2, 11],
 [17, 5],
 [17, 26],
 [14, 5]]

In [6]:
max_length=3
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
padded_reviews

array([[29, 10,  0],
       [ 2, 26,  0],
       [28,  2,  0],
       [13, 19,  4],
       [21,  2, 25],
       [11, 10,  0],
       [17,  2, 11],
       [17,  5,  0],
       [17, 26,  0],
       [14,  5,  0]])

In [10]:

embedded_vector_size=4
model=Sequential()
model.add(Embedding(vocab_size,embedded_vector_size,input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [11]:

X=padded_reviews
y=sentiment

In [12]:

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [13]:

model.fit(X,y,epochs=50,verbose=0)

In [14]:

loss,accuracy=model.evaluate(X,y)
accuracy

1/1 [==============================] - 1s 635ms/step - loss: 0.6351 - accuracy: 1.0000


1.0

In [15]:

model.get_layer('embedding').get_weights()[0]

array([[ 0.07392912,  0.04252484, -0.10278057,  0.02705304],
       [ 0.0358067 ,  0.04880342, -0.03825196,  0.04793814],
       [-0.01578412,  0.02271023, -0.08258314, -0.03018119],
       [ 0.01907246, -0.04204499, -0.03180754, -0.01939954],
       [-0.04840605, -0.06066139,  0.04092752, -0.01992084],
       [ 0.07300803, -0.01748651,  0.08833597,  0.04205032],
       [ 0.00808771,  0.00796262, -0.04366335, -0.03502352],
       [ 0.00137877,  0.0110983 ,  0.01295451, -0.01412668],
       [-0.02855686, -0.02330015, -0.04881635, -0.01322041],
       [ 0.01325378,  0.00749149, -0.01128425, -0.01358304],
       [ 0.00464269, -0.03584737,  0.02882807, -0.00104947],
       [ 0.08573142,  0.06084308,  0.01162947,  0.07213335],
       [-0.00701349,  0.01754924,  0.04593548,  0.02720506],
       [ 0.09900276,  0.06830219, -0.08121967, -0.06964158],
       [-0.00888991, -0.01264002,  0.0495642 ,  0.09203525],
       [-0.0390778 , -0.02092934, -0.02947463,  0.03622924],
       [ 0.04261526, -0.

In [17]:
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [18]:

weights[29]

array([ 0.08529758,  0.0952803 , -0.06146235, -0.05349411], dtype=float32)

In [19]:
weights[10]

array([ 0.00464269, -0.03584737,  0.02882807, -0.00104947], dtype=float32)